openapi: 3.0.3
info:
  title: Restaurant Service
  description: "Restaurant Service Application"
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8080

paths:
  /restaurants:
    get:
      operationId: getRestaurants
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/rating'
        - $ref: '#/components/parameters/distance'
        - $ref: '#/components/parameters/price'
        - $ref: '#/components/parameters/cuisine'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'

components:
  parameters:
    name:
      name: name
      in: query
      description: Name
      required: false
      schema:
        type: string
    rating:
      name: rating
      in: query
      description: Customer Rating
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 5
    distance:
      name: distance
      in: query
      description: Distance
      required: false
      schema:
        minimum: 1
        maximum: 10
        type: integer
    price:
      name: price
      in: query
      description: Price
      required: false
      schema:
        type: integer
        minimum: 10
        maximum: 50
    cuisine:
      name: cuisine
      in: query
      description: Cuisine
      required: false
      schema:
        type: string
  schemas:
    Error:
      type: object
      properties:
        description:
          type: string
        field:
          type: string
        value:
          type: string
    Restaurant:
      type: object
      properties:
        name:
          type: string
          example: Five Guys
        rating:
          type: integer
          example: 4
        price:
          type: integer
          example: 10
        distance:
          type: integer
          example: 5
        cuisine:
          type: string
          example: Italian